#! /bin/bash

if [ -z "$DB_DIR" ]; then
    echo "Need to set DB_DIR"
    exit 1
fi
if [ ! -d "$DB_DIR" ]; then
    echo "Need to create directory DB_DIR"
    exit 1
fi
if [ "$(ls -A $DB_DIR)" ]; then
    echo "$DB_DIR contains files, cannot run script"
    exit 1
fi

# $SOURCE1 and $TAR1 both get exported to this script.
# For example, see stress-suite.

if [ ! -f ${SOURCE1}/${TAR1}.tar.gz ] ; then
    echo "Unable to locate file ${SOURCE1}/${TAR1}.tar.gz"
    exit 1
fi

pushd ${DB_DIR}

echo "untarring ${SOURCE1}/${TAR1}..."
tar xzf ${SOURCE1}/${TAR1}.tar.gz

popd

#export BASEDIR1=${DB_DIR}/${TAR1}
#export VARDIR1=${DB_DIR}/vardir1

rm -rf ${VARDIR1}
mkdir ${VARDIR1}

RQG_DIR=/home/joel/randgen

export numQueries=10000000
export numThreads=64
export secDuration=300
#export debugSwitch=--debug
export sqlLog1=--mysqld=--general_log


pushd ${RQG_DIR}
./runall.pl --grammar=conf/${DOMAIN_DIR}/${grammar} --duration=${secDuration} --queries=${numQueries} --threads=${numThreads} --basedir=${BASEDIR1} --vardir=${VARDIR1} --mysqld=--default-storage-engine=TokuDB ${debugSwitch} ${sqlLog1}
popd
